include:
    - base.avahi
    - base.journald
    - base.localgit
    - base.minion
    - base.mnt_jenkins
    - base.sound
    - base.sources
    - base.syslog
    - base.timesyncd
    - base.tsocks
