include:
    - slave.localgit
    - slave.chmodtty
    - slave.logind
    - slave.sudoers
    - slave.sysctl
    - slave.tsocks
    - slave.grub
    - slave.timesyncd
    - slave.packages
    - slave.ssh_keys
