include:
    - slave.localgit
    - slave.chmodtty
    - slave.logind
    - slave.sound
    - slave.sources
    - slave.sudoers
    - slave.sysctl
    - slave.tsocks
    - slave.grub
    - slave.timesyncd
    - slave.minion
    - slave.journald
    - slave.packages
    - slave.ssh_keys
